### Health

GET http://localhost:8080/health

### Create Problem

POST http://localhost:8080/problems
Content-Type: application/json
Accept: application/json

{
  "title": "Binary Search",
  "difficulty": "EASY",
  "algorithm": "Binary Search",
  "solved": false,
  "notes": "Review left and right limits",
  "url": "https://leetcode.com/problems/binary-search/"
}

### Create Problem with title onlyx

POST http://localhost:8080/problems
Content-Type: application/json
Accept: application/json

{
  "title": "Binary Search"
}

### Create Problem - Bad Difficulty

POST http://localhost:8080/problems
Content-Type: application/json
Accept: application/json

{
  "title": "Binary Search",
  "difficulty": "IMPOSSIBLE",
  "algorithm": "Binary Search",
  "solved": false,
  "notes": "Review left and right limits",
  "url": "https://leetcode.com/problems/binary-search/"
}

### Create problem - Empty title (400 Bad Request)

POST http://localhost:8080/problems
Content-Type: application/json
Accept: application/json

{
  "title": "",
  "difficulty": "EASY",
  "algorithm": "Hash Map",
  "solved": false,
  "notes": "Testing global exception handler",
  "url": "https://leetcode.com/problems/two-sum/"
}

### Get Problems

GET http://localhost:8080/problems

### Get Problem by id (exists)

GET http://localhost:8080/problems/3

### Get Problem by id (not found)

GET http://localhost:8080/problems/99999

### Get Problems by Difficulty

GET http://localhost:8080/problems?difficulty=EASY

### Get Problem by invalid difficulty

GET http://localhost:8080/problems?difficulty=IMPOSSIBLE

### Get Problems by Solved

GET http://localhost:8080/problems?solved=true

### Get Problems by invalid solved

GET http://localhost:8080/problems?solved=invalid

### Get Problems by Difficulty and Solved

GET http://localhost:8080/problems?difficulty=EASY&solved=false

### Get Problems paginated

GET http://localhost:8080/problems?page=0&size=3

### Order by id ascending

GET http://localhost:8080/problems?page=0&size=10&sort=id,asc

### Order by id descending

GET http://localhost:8080/problems?page=0&size=10&sort=id,desc

### Update problem

PUT http://localhost:8080/problems/3
Content-Type: application/json
Accept: application/json

{
  "title": "Longest Substring Without Repeating Characters",
  "difficulty": "MEDIUM",
  "algorithm": "SLIDING_WINDOW",
  "solved": true,
  "notes": "Solved using a sliding window with a HashSet.",
  "url": "https://leetcode.com/problems/binary-search/"
}

### Update non-existing problem

PUT http://localhost:8080/problems/99999
Content-Type: application/json
Accept: application/json

{
  "title": "Test",
  "difficulty": "EASY",
  "algorithm": "ARRAY",
  "solved": false,
  "notes": "Test",
  "url": "https://example.com"
}

### Delete existing problem

DELETE http://localhost:8080/problems/10

### Delete non-existing problem

DELETE http://localhost:8080/problems/99999



