###

### Health

GET http://localhost:8080/health

###

### Create Problem

POST http://localhost:8080/problems
Content-Type: application/json

{
  "title": "Binary Search",
  "difficulty": "Easy",
  "algorithm": "Binary Search",
  "solved": false,
  "notes": "Review left and right limits",
  "url": "https://leetcode.com/problems/binary-search/"
}

###

### Create problem - Empty title (400 Bad Request)

POST http://localhost:8080/problems
Content-Type: application/json

{
  "title": "",
  "difficulty": "Easy",
  "algorithm": "Hash Map",
  "solved": false,
  "notes": "Testing global exception handler",
  "url": "https://leetcode.com/problems/two-sum/"
}
###

### Get Problems

GET http://localhost:8080/problems

###

### Get Problem by id (exists)

GET http://localhost:8080/problems/1

###

### Get Problem by id (not found)

GET http://localhost:8080/problems/99999

###

### Update problem

PUT http://localhost:8080/problems/1
Content-Type: application/json
Accept: application/json

{
  "title": "Longest Substring Without Repeating Characters",
  "difficulty": "MEDIUM",
  "algorithm": "SLIDING_WINDOW",
  "solved": true,
  "notes": "Solved using a sliding window with a HashSet.",
  "url": "https://leetcode.com/problems/binary-search/"
}

###

### Update non-existing problem

PUT http://localhost:8080/problems/99999
Content-Type: application/json
Accept: application/json

{
  "title": "Test",
  "difficulty": "EASY",
  "algorithm": "ARRAY",
  "solved": false,
  "notes": "Test",
  "url": "https://example.com"
}

###

### Delete existing problem

DELETE http://localhost:8080/problems/8
Accept: application/json

###

### Delete non-existing problem

DELETE http://localhost:8080/problems/99999
Accept: application/json



